#!/bin/bash

pdflatex main
if [ $? != 0 ] ; then echo "latex round 1 failed failed!" ; exit 1 ; fi

#bibtex main
#if [ $? != 0 ] ; then echo "bibtex round 1 failed!" ; exit 1 ; fi
#
#pdflatex main
#if [ $? != 0 ] ; then echo "latex round 2 failed!" ; exit 1 ; fi
#
#bibtex main
#if [ $? != 0 ] ; then echo "bibtex round 2 failed!" ; exit 1 ; fi
#
pdflatex main
if [ $? != 0 ] ; then echo "latex round 3 failed!" ; exit 1 ; fi

open main.pdf
